spring:
  application:
    name: HelloClient

server:
  port: 7211

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.cloud.client.ip-address:${server.port}}}

endpoints:
  restart:
    enabled: true