spring:
  application:
    name: HelloServer

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.cloud.client.ip-address:${server.port}}}