server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    perfer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false
